module.exports = {
  apps: [
    {
      name: "bot",
      cwd: __dirname,
      script: "python",
      args: "-m group_chat_telegram_ai.bot",
      autorestart: true,
      watch: false,
      out_file: "logs/bot.out.log",
      error_file: "logs/bot.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        PYTHONUNBUFFERED: "1",
        PYTHONPATH: "src",
      },
    },
    {
      name: "onboarding",
      cwd: __dirname,
      script: "python",
      args: "-m group_chat_telegram_ai.run_onboarding",
      autorestart: true,
      watch: false,
      out_file: "logs/bot.out.log",
      error_file: "logs/bot.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        PYTHONUNBUFFERED: "1",
        PYTHONPATH: "src",
      },
    },
    {
      name: "dayly",
      script: "scripts/run_daily_report.sh",
      interpreter: "bash",
      cron_restart: "30 14 * * *",
      autorestart: false,
      watch: false,
      out_file: "logs/daily_report.out.log",
      error_file: "logs/daily_report.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        REPORT_TZ: process.env.REPORT_TZ || "UTC",
        REPORT_SEND: process.env.REPORT_SEND || "true",
        PYTHON_BIN: process.env.PYTHON_BIN || "python",
      },
    },
    {
      name: "weekly",
      script: "scripts/run_weekly_report.sh",
      interpreter: "bash",
      cron_restart: "30 16 * * 0",
      autorestart: false,
      watch: false,
      out_file: "logs/weekly_report.out.log",
      error_file: "logs/weekly_report.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        REPORT_TZ: process.env.REPORT_TZ || "UTC",
        REPORT_SEND: process.env.REPORT_SEND || "true",
        PYTHON_BIN: process.env.PYTHON_BIN || "python",
      },
    },
    {
      name: "monthly",
      script: "scripts/run_monthly_report.sh",
      interpreter: "bash",
      cron_restart: "45 16 * * *",
      autorestart: false,
      watch: false,
      out_file: "logs/monthly_report.out.log",
      error_file: "logs/monthly_report.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        REPORT_TZ: process.env.REPORT_TZ || "UTC",
        REPORT_SEND: process.env.REPORT_SEND || "true",
        PYTHON_BIN: process.env.PYTHON_BIN || "python",
      },
    },
    {
      name: "morning_plan_job",
      script: "scripts/run_morning_plan.sh",
      interpreter: "bash",
      cron_restart: "0 23 * * *",
      autorestart: false,
      watch: false,
      out_file: "logs/morning_plan.out.log",
      error_file: "logs/morning_plan.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        REPORT_TZ: process.env.REPORT_TZ || "UTC",
        REPORT_SEND: process.env.REPORT_SEND || "true",
        PYTHON_BIN: process.env.PYTHON_BIN || "python",
      },
    },
  ],
};
